### ISSUE TITLE
add more possibilities into condition tests

### ISSUE THREAD

**Issue by wcastand** [graphile/gatsby-source-pg#1]
Hi, i couldn't find an answer so ;aybe it's not possible right now>

Is it possible to use condition other than equality in condition ?
i assume you are using this packages so it should be possible ? [postgraphile-plugin-connection-filter](https://github.com/graphile-contrib/postgraphile-plugin-connection-filter)

it would be nice to do something like this for example : 
```graphql
{
  postgres {
    allPosts(condition: {createdAt: ["<=", "2019-01-07"] }) {
      totalCount
    }
  }
}

```

```graphql
{
  postgres {
    allPosts(condition: {createdAt: [ ["<=", "2019-01-07"], [">=", "2018-12-07"] ] }) {
      totalCount
    }
  }
}

```

do you think that would be possible ?

**Comment by benjie** [comment]
Sure; since it uses PostGraphile you should be able to use any of the plugins for PostGraphile - see the Customising section in the README:

https://github.com/graphile/gatsby-source-pg#customising

In this case:

```js
// gatsby-config.js
module.exports = {
  /* ... */
  plugins: [
    /* ... */
    {
      resolve: "gatsby-source-pg",
      options: {
        connectionString: "postgres:///mydb",
        schema: "public",

        /* 👇 */
        appendPlugins: [
          require("@graphile-contrib/pg-simplify-inflector"),
          require("postgraphile-plugin-connection-filter"),
        ],
        /* 👆 */
      },
    },
  ],
};
```
