### ISSUE TITLE
Error on connecting 

### ISSUE THREAD

**Issue by Masarsah** [graphile/gatsby-source-pg#15]
Thank you for the plugin I try to connect my database I got this source and transform nodes - 803.113s
and when I remove schema: `public`, its build but with out connect to server 
`{
      resolve: `gatsby-source-pg`,
      options: {
        connectionString: `postgres://username@localhost:5432/db`,
        schema: `public`,
        refetchInterval: 60, // Refetch data every 60 seconds
      },
    },`

**Comment by benjie** [comment]
How big is your database schema?

**Comment by benjie** [comment]
Closing this issue due to no response. Feel free to re-open with an answer to the above question and any more information that may help pinpoint the reason for this :+1:
