### ISSUE TITLE
How to use pagination?

### ISSUE THREAD

**Issue by ramusbucket** [graphile/gatsby-source-pg#2]
I understand how to use pagination in GraphQL query but how Gatsby is going to generate all the pages with N items per page?

**Comment by benjie** [comment]
Gatsby has a page on pagination: https://www.gatsbyjs.org/docs/adding-pagination/ their `skip` and `limit` become `offset` and `first` respectively with this plugin. If this doesn’t answer your question please reopen this issue and expand on what you need.

**Comment by ramusbucket** [comment]
Yes, indeed it answers my question. You are awesome! Thank you.
