### ISSUE TITLE
Option to Not Disable Mutations

### ISSUE THREAD

**Issue by machineghost** [graphile/gatsby-source-pg#21]
I realize that in most Gatsby apps there's no need for mutations, but what if you want to be able to edit your database from your dev server (before deploying ... ie. if you want to create a mini-CMS on your dev server)?

It seems like Gatsby/Gatsby-source-pg should be fully capable of serving mutations, since it just leverages Postgraphile, and that tool certainly can make mutations ... but if I just try to change `createSchema.js` like so:

    const skipPlugins = [
      graphileBuild.QueryPlugin,
      // graphileBuild.MutationPlugin,
      graphileBuild.SubscriptionPlugin,
    ];

the queries stop working, presumably because of whatever is going on in RenamedQueryPlugin.

I'd be happy to submit a PR with a `RenamedMutationPlugin` and whatever else is needed to add some sort of `enableMutations: true` option, if A) someone could take a quick sec to explain what's going on there, and B) if such a PR would actually be desired.

If it's just a goal to keep this plug-in read-only then I guess I'll just have to run a duplicate/parallel Postgraphile server (which isn't the end of the world, just sub-optimal).

**Comment by fcFn** [comment]
AFAIU, the source queries are run at build time, so the data that is taken through sources has to be static. But you can still use Postgraphile directly for mutations.

**Comment by benjie** [comment]
Exactly; it does not make sense to have mutations inside of the Gatsby plugin system, but you can absolutely run PostGraphile directly in development; see: https://www.graphile.org/postgraphile/usage-cli/

**Comment by machineghost** [comment]
Ok, but ... you literally describe merging the dynamic stuff and the static stuff on https://www.gatsbyjs.org/docs/data-fetching/.

Plus ... let's say I'm using Strapi (or any other CMS).  I have a database with my data, I edit it with Strapi, and I display it in Gatsby.  All I'm trying to do here IS THE EXACT SAME THING ... just with the edit UI in my app instead of in Strapi.

I totally get the idea that data providers are read-only ... but I think you're ignoring a lot of Gatsby use cases by pretending no one ever wants to use their app to edit data.  Just because they're not using Strapi, it doesn't make doing the same thing wrong.

**Comment by benjie** [comment]
The documentation you linked to seems to outline that there’s a difference to build-time queries (gatsby-source-graphql) and runtime queries (using fetch API) which is exactly what I’m saying. The build time API doesn’t run a server, there’s no HTTP, so querying it with fetch cannot happen and adding mutations to it does not make sense since it’s not something that would ever happen at build time in Gatsby. To run runtime queries/mutations you need a server; that’s a separate concern to build-time querying, so it must be handled separately. You can run a runtime PostGraphile server in many ways, I linked you to the easiest.

If you have an issue with Gatsby’s chosen architecture I suggest you take it up with Gatsby, we just wrote a plugin to make it easier to pull data from Postgres within Gatsby build time.

**Comment by benjie** [comment]
If you like, you could run a PostGraphile server and then use gatsby-source-graphql to pull from it directly, completely bypassing this plugin. Then you’d have only one “server”, which might appease your concerns? Personally I think the Gatsby architecture using a plugin for build is the right direction.

**Comment by machineghost** [comment]
>If you have an issue with Gatsby’s chosen architecture I suggest you take it up with Gatsby, we just wrote a plugin to make it easier to pull data from Postgres within Gatsby build time.

I apologize if I came across as "having an issue with Gatsby's chosen" *anything*; that was not my intent.  As I said before, I was just trying to draw parallels to a scenario Gatsby is explicitly designed for: working with a headless CMS. I don't think it's controversial to say that Gatsby supports:

A) data editing outside the client at build time (eg. using the UI of a headless CMS)

B) data editing inside the client at run-time (eg. using the API of a headless CMS)

All I was trying to suggest was that a single flag in this plug-in could allow *exactly* what I described above ... only:

A) instead of relying on a separate headless CMS API, just use the API already running, in the already running dev server

B) instead of using someone else's UI, use your own, and run it in the dev server (that again, you're already running)

I'm not trying to argue or attack anyone's architecture, and from where I sit I'm really not asking for anything philosophically radically opposed to Gatsby: I literally just want to use what's already there (Gatsby dev server and Postgraphile), in place of the established Gatsby pattern of doing the exact same thing, but with separate tools.

Now, IF you follow my logic, being able to set a flag here would be (I think) a superior solution  to having to re-do everything this library does that `gatsby-source-graphql` doesn't.  But of course it's not a huge deal to use `gatsby-source-graphql`, and if you truly think what I'm describing is philosophically or architecturally opposed to Gatsby, then *of course* it shouldn't be encouraged, and `gatsby-source-graphql` is the correct answer here.

**Comment by benjie** [comment]
Ah I see; the dev server’s GraphQL endpoint. I’ve never seen anything (except GraphiQL) query that directly, normally you use Gatsby’s special exports to automagically query it. Correct me if I’m wrong; I don’t think Gatsby’s schema through the dev server supports mutations?

**Comment by machineghost** [comment]
I'm honestly not familiar enough with how Gatsby handles endpoints to answer that.

My thinking was just ... would it actually break Gatsby to have mutations on the API that it never uses?  I wouldn't imagine so (I'd *imagine* all it would care about is "do we have the queries I need?"). Thus, my logic was that telling Postgraphile not to hide those mutations wouldn't break (or even affect) Gatsby in any way... but it would let non-Gatsby code utilize those mutations.

But you likely know way more about that that I do, and obviously if there is some technical restriction, then that sinks my whole idea.  I just thought the opposition was more philosophical: that a "source plug-in" should only "source" (read) data.  _If_ that was the only issue, I was trying to sell the idea that "well yes, mostly, but would one tiny flag that opens up the possibility of 'a STRAPI-like UI' in your ev environment" as an acceptable exception to that rule.

**Comment by benjie** [comment]
I see what you're saying. For now, the solution is a separate PostGraphile server for runtime operations :+1:
