### ISSUE TITLE
Source image as a dynamic data

### ISSUE THREAD

**Issue by uded** [graphile/gatsby-source-pg#28]
I am looking into sourcing images via PG as a field. I was trying to investigate if there is a simple, easy way to achieve this with some simple code, but currently -- I can't really find one.

Before I will dig in into creating a graphile plugin to handle this, can someone direct me to a ready-to-use solution?

**Comment by benjie** [comment]
There’s a BYTEA plugin example in one of the issues on GitHub that might help.

**Comment by uded** [comment]
I am not sure if I want to actually source a byte data via DB, or rather just be able to _link_ an image by name and/or path and some metadata or effectively provide an external URL to process them.

This seems simple at the first glance, but it's also a complex scenario in Gatsby due to its nature as I am learning now. So, I am trying to figure out the best course of action for this...

**Comment by benjie** [comment]
Thanks for sharing your solution :raised_hands:

**Comment by uded** [comment]
My pleasure. But, as I said, it's not perfect. And while being in line with Gatsby philosophy, I am digging into this further. Possibly to make it more flexible (currently it will only work with remote URLs, meaning Gatsby will download and process them) and more performant. I will update this ticket if I will make a better one...

**Comment by reediculous456** [comment]
This really helped me out! Please consider adding this to the docs for the plugin
