### ISSUE TITLE
Not working with gatsby 2.2.11

### ISSUE THREAD

**Issue by ramusbucket** [graphile/gatsby-source-pg#3]
I created a fresh project with `gatsby new . ` Got some warnings as below - 

```
warning "gatsby > eslint-plugin-graphql@2.1.1" has incorrect peer dependency "graphql@^0.12.0 || ^0.13.0".
warning "gatsby > express-graphql@0.6.12" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
warning "gatsby > graphql-tools@3.1.1" has incorrect peer dependency "graphql@^0.13.0".
```

But this did not prevent me using GraphQL for siteMetadata queries. But as soon as I added this plugin for my Postgres data `GraphiQL` playground started complaining as below error - 

```
"message": "Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules directory. If different versions of "graphql" are the dependencies of other relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different versions may have different capabilities and behavior. The data from one version used in the function from another could produce confusing and spurious results.",
```
Because of above error, neither GraphiQL nor application is getting any data from Postgres

My environment: 
Node - v11.6.0
gatsby-cli - v2.4.17
gatsby - v2.2.11
gatsby-source-pg - v0.1.2

Please advise. Thanks.

**Comment by benjie** [comment]
This means there’s multiple versions of graphql in your node_modules folder. You can use the yarn resolutions feature (linked to in the error message) to solve this. Different versions of graphql don’t work together, so you have to ensure there is only one version.

Another solution may be to delete your lock file(s) and node_modules and reinstall.

**Comment by ramusbucket** [comment]
You are absolutely right. I read and understood the message the way you are explaining it. From the version requirements I can deduce that I can either live with `graphql` v14.1.1 or v0.13.2 but the moment I add resolution for one of these versions, graphql stops working. May be I'm not putting all resolutions correctly. Thanks!

**Comment by ramusbucket** [comment]
For anyone who stumbles upon this... here is how I could get it resolved..

Ahh.. finding out correct version is tricky..

I created fresh project with `gatsby new <project_name>` and did `npm install`.
Installed plugin with `npm install --save gatsby-source-pg` 

After this I searched for folders named `graphql` in `node_modules` and then prepared following resolution list - 

      "resolutions":{
        "eslint-plugin-graphql/graphql": "14.1.1",
        "express-graphql/graphql": "14.1.1",
        "graphql-tools/graphql": "14.1.1",
        "apollo-link/graphql": "14.1.1",
        "apollo-utilities/graphql": "14.1.1",
        "gatsby-source-graphql/graphql": "14.1.1",
        "gatsby-source-pg/graphql": "14.1.1",
        "@types/graphql": "14.1.1"
      }

But then somehow, when I did `yarn install`, `@types` said that it did not like `14.1.1` and and offered a range of versions. I choose the latest one from the presented list, `14.0.7` and went ahead with installation. It still generated warnings as below - 

    yarn install
    yarn install v1.12.3
    info No lockfile found.
    [1/4] Resolving packages...
    Couldn't find any versions for "@types/graphql" that matches "14.1.1"
    ? Please choose a version of "@types/graphql" from this list: 14.0.7
    warning Resolution field "graphql@14.1.1" is incompatible with requested version "graphql@0.13.x"
    [2/4] Fetching packages...
    info fsevents@1.2.7: The platform "win32" is incompatible with this module.
    info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning "gatsby > express-graphql@0.6.12" has incorrect peer dependency "graphql@^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0".
    warning "gatsby > eslint-plugin-graphql@2.1.1" has incorrect peer dependency "graphql@^0.12.0 || ^0.13.0".
    warning "gatsby > graphql-tools@3.1.1" has incorrect peer dependency "graphql@^0.13.0".
    warning "gatsby > pnp-webpack-plugin > ts-pnp@1.0.1" has unmet peer dependency "typescript@*".
    warning "gatsby-source-pg > gatsby-source-graphql > apollo-link@1.2.1" has incorrect peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0".
    [4/4] Building fresh packages...
    success Saved lockfile.
    Done in 37.83s.

But now, I can use `GraphiQL` playground to execute my graphql queries and in the project as well.

**Comment by benjie** [comment]
@ramusbucket try:

```
“resolutions”:{
“graphql”:”14.x”
}
```

Sorry about smart quotes, am on phone.

**Comment by ramusbucket** [comment]
aha... this is even better... That's why expert's opinion matters. This worked like a charm without any steps above (from my comment). Awesome!
