### ISSUE TITLE
gatsby-source-pg incompatible with gatsby 4

### ISSUE THREAD

**Issue by dmangust** [graphile/gatsby-source-pg#37]
### Summary

gatsby-source-pg incompatible with gatsby 4

gatsby build:

Calling `addThirdPartySchema` in the `sourceNodes` API is deprecated. Please use: `createSchemaCustomization`

There was an error in your GraphQL query:

Cannot query field "postgres" on type "Query".

**Comment by benjie** [comment]
Resolved in v1.0.0-rc.0
