### ISSUE TITLE
Update to graphql 16

### ISSUE THREAD

**Issue by danielkochdakitec** [graphile/gatsby-source-pg#54]
### Summary

Please update the package so we can use Gatsby v5. I guess it is necessary to update the graphql dependency from:
```
"graphql": "^0.13.x | ^14.0.0 | ^15.0.0",
```
to also be compatible with graphl 16 since Gatsby uses graphl ^16.6.0

**Comment by benjie** [comment]
Unfortunately PostGraphile V4 cannot support GraphQL v16 (at least not without significant work):

https://github.com/graphile/graphile-engine/pull/764#issuecomment-1055726062

PostGraphile V5 will be released at some point this year and supports GraphQL v16, once that's out we can use it for this Gatsby source. In the mean time, you might consider using PostGraphile as a remote schema using `gatsby-source-graphql` directly.

**Comment by danielkochdakitec** [comment]
Thank you for this insight! What I did for now is I put a resolution in my package.json:

```
"resolutions": {
        "@types/react": "^17.0.38",
        "graphql": "15.8.0"
    },
```

This might not be the best solution, but at least it is a temporary workaround for me.
